include: ['.well-known']

defaults:
  - # Set default layouts
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'default'
  -
    scope:
      path: 'typefaces'
      type: 'pages'
    values:
      layout: 'detail'
  -
    scope:
      path: 'glyphs'
      type: 'pages'
    values:
      layout: 'glyphs'
  -
    scope:
      path: 'categories'
      type: 'pages'
    values:
      layout: 'category'
  - # Set default body classes for type detail pages
    scope:
      path: 'typefaces/display'
      type: 'pages'
    values:
      body-class: 'display detail'
  -
    scope:
      path: 'typefaces/monospaced'
      type: 'pages'
    values:
      body-class: 'monospaced detail'
  -
    scope:
      path: 'typefaces/sans-serif'
      type: 'pages'
    values:
      body-class: 'sans-serif detail'
  -
    scope:
      path: 'typefaces/serif'
      type: 'pages'
    values:
      body-class: 'serif detail'
  - # Set default body classes for glyph explorer pages
    scope:
      path: 'glyphs/display'
      type: 'pages'
    values:
      body-class: 'display glyphs'
  -
    scope:
      path: 'glyphs/monospaced'
      type: 'pages'
    values:
      body-class: 'monospaced glyphs'
  -
    scope:
      path: 'glyphs/sans-serif'
      type: 'pages'
    values:
      body-class: 'sans-serif glyphs'
  -
    scope:
      path: 'glyphs/serif'
      type: 'pages'
    values:
      body-class: 'serif glyphs'
